In [ ]:
import os
import torch
import pandas as pd
import numpy as np
from tqdm import tqdm
from concurrent.futures import ThreadPoolExecutor, as_completed

# H.sapiens Files

In [11]:
H_phenotype_chemicalentity = 'ALL_PHENOTYPE_CHEMICALENTITY.csv'
H_mutation_disease = 'ALL_MUTATION_DISEASE.csv'
H_molecularfunction_chemicalentity = 'ALL_MOLECULARFUNCTION_CHEMICALENTITY.csv'
H_disease_anatomy = 'ALL_DISEASE_ANATOMY.csv'
H_chemicalentity_disease = 'ALL_CHEMICALENTITY_DISEASE.csv'
H_disease_disease = 'ALL_DISEASE_DISEASE.csv'
H_biologicalprocess_gene = 'ALL_BIOLOGIALPROCESS_GENE.csv'
H_protein_protein = 'ALL_PROTEIN_PROTEIN.csv'
H_gene_phenotype = 'ALL_GENE_PHENOTYPE.csv'
H_protein_disease = 'ALL_PROTEIN_DISEASE.csv'
H_anatomy_gene = 'ALL_ANATOMY_GENE.csv'
H_chemicalentity_biologicalprocess = 'ALL_CHEMICALENTITY_BIOLOGICALPROCESS.csv'
H_disease_gene = 'ALL_DISEASE_GENE.csv'
H_gene_cellularcomponent = 'ALL_GENE_CELLULARCOMPONENT.csv'
H_chemicalentity_chemicalentity = 'ALL_CHEMICALENTITY_CHEMICALENTITY.csv'
H_cellularcomponent_gene = 'ALL_CELLCOMPONENT_GENE.csv'
H_gene_disease = 'ALL_GENE_DISEASE.csv'
H_protein_cellularcomponent = 'ALL_PROTEIN_CELLULARCOMPONENT.csv'
H_protein_phenotype = 'ALL_PROTEIN_PHENOTYPE.csv'
H_mutation_protein = 'ALL_MUTATION_PROTEIN.csv'
H_chemicalentity_gene = 'ALL_CHEMICALENTITY_GENE2.csv'
H_chemicalentity_tissue = 'ALL_CHEMICALENTITY_TISSUE.csv'
H_chemicalentity_protein = 'ALL_CHEMICALENTITY_PROTEIN2.csv'
H_biologicalprocess_biologicalprocess = 'ALL_BIOLOGICALPROCESS_BIOLOGICALPROCESS.csv'
H_phenotype_phenotype = 'All_PHENOTYPE_PHENOTYPE.csv'
H_phenotype_gene = 'ALL_PHENOTYPE_GENE.csv'
H_chemicalentity_inhibits_biologicalprocess = 'ALL_CHEMICALENTITY_INHIBITS_BIOLOGICALPROCESS.csv'
H_gene_inhibits_biologicalprocess = 'ALL_GENE_INHIBITS_BIOLOGICALPROCESS.csv'
H_protein_biologicalprocess = 'ALL_PROTEIN_BIOLOGICALPROCESS.csv'
H_gene_promotes_biologicalprocess = 'ALL_GENE_PROMOTES_BIOLOGICALPROCESS.csv'
H_gene_molecularfunction = 'ALL_GENE_MOLECULARFUNCTION.csv'
H_gene_pathway = 'ALL_GENE_PATHWAY.csv'
H_chemicalentity_pathway = 'ALL_CHEMICALENTITY_PATHWAY.csv'
H_gene_tissue = 'ALL_GENE_TISSUE.csv'
H_disease_phenotype = 'ALL_DISEASE_PHENOTYPE.csv'
H_chemicalentity_mutation = 'ALL_CHEMICALENTITY_MUTATION.csv'
H_gene_anatomy = 'ALL_GENE_ANATOMY.csv'
H_phenotype_disease = 'ALL_PHENOTYPE_DISEASE.csv'
H_pathway_gene = 'ALL_PATHWAY_GENE.csv'
H_disease_chemicalentity = 'ALL_DISEASE_CHEMICALENTITY.csv'
H_disease_mutation = 'ALL_DISEASE_MUTATION.csv'
H_gene_chemicalentity = 'ALL_GENE_CHEMICAL.csv'
H_protein_pathway = 'ALL_PROTEIN_PATHWAY.csv'
H_gene_protein = 'ALL_GENE_PROTEIN.csv'
H_gene_noeffect_biologicalprocess = 'ALL_GENE_NOEFFECT_BIOLOGICALPROCESS.csv'
H_chemicalentity_promotes_biologicalprocess = 'CHEMICALENTITY_PROMOTES_BIOLOGICALPROCESS/ALL_CHEMICALENTITY_PROMOTES_BIOLOGICALPROCESS.csv'
H_gene_biologicalprocess = 'ALL_GENE_BIOLOGICALPROCESS.csv'
H_protein_molecularfunction = 'ALL_PROTEIN_MOLECULARFUNCTION.csv'
H_mutation_gene = 'MUTATION_GENE/ALL_MUTATION_GENE.csv'
H_gene_gene = 'ALL_GENE_GENE.csv'
H_molecularfunction_molecularfunction = 'ALL_MOLECULARFUNCTION_MOLECULARFUNCTION.csv'
H_gene_mutation = 'ALL_GENE_MUTATION.csv'
H_molecularfunction_biologicalprocess = 'ALL_MOLECULARFUNCTION_BIOLOGICALPROCESS.csv'
H_protein_tissue = 'ALL_PROTEIN_TISSUE.csv'
H_cellularcomponent_cellularcomponent = 'ALL_CELLULARCOMPONENT_CELLULARCOMPONENT.csv'
H_pathway_pathway = 'ALL_PATHWAY_PATHWAY.csv'
H_anatomy_anatomy = 'ALL_ANATOMY_ANATOMY.csv'
H_biologicalprocess_chemicalentity ='ALL_BIOLOGICALPROCESS_CHEMICALENTITY.csv'
H_plant_chemicalentity = 'ALL_PLANTSPECIES_CHEMICAL.csv'
H_plant_disease = 'ALL_PLANTSPECIES_DISEASE.csv'

# S.cerevisae files

In [12]:
Y_Gene_ph = 'ALL_YEAST_GENEORTHO_PHENOTYPE.csv'
Y_Ch_Ch = 'ALL_YEAST_CHEMICALENTITY_CHEMICALENTITY.csv'
Y_Ch_Gene = 'ALL_CHEMICALENTITY_GENEORTHO.csv'
Y_Gene_CellComp = 'ALL_YEAST_GENEORTHO_CELLULARCOMPONENT.csv'
Y_Gene_Gene = 'ALL_YEAST_GENEORTHO_GENEORTHO.csv'

# Aging Associated
Y_Gene_Inhibits_BioPro = 'Yeast_GeneORTHO_Inhibits_BiologicalProcess.csv'
Y_Gene_Promotes_BioPro = 'Yeast_GeneORTHO_Promotes_BiologicalProcess.csv'
Y_Ch_Inhibits_BioPro = 'Yeast_ChemicalEntity_Inhibits_BiologicalProcess.csv'


# C.elegans files

In [13]:
C_Gene_ph = 'ALL_CELE_GENEORTHO_PHENOTYPE.csv'
C_Ch_Gene = 'ALL_CELE_CHEMICALENTITY_GENEORTHO.csv'
C_Gene_Gene = 'ALL_CELE_GENEORTHO_GENEORTHO.csv'

C_Ch_promotes_BioPro = 'Cele_ChemicalEntity_Promotes_BiologicalProcess.csv'
C_Pro_Tiss = 'Cele_Protein_Tissue.csv'
C_Ch_inhibits_BioPro = 'Cele_ChemicalEntity_Inhibits_BiologicalProcess.csv'

C_Gene_promotes_BioPro = 'ALL_Celegans_GeneORTHO_Promotes_BiologicalProcess.csv'
C_Gene_BioPro = 'ALL_Celegans_GeneORTHO_BiologicalProcess.csv'
C_Gene_inhibits_BioPro = 'ALL_Celegans_GeneORTHO_Promotes_BiologicalProcess.csv'

# D.melanogaster files


In [14]:
D_Gene_ph = 'ALL_DROSO_GENEORTHO_PHENOTYPE.csv'
D_Ch_Gene = 'ALL_DROSO_CHEMICALENTITY_GENEORTHO.csv'
D_Gene_Gene = 'ALL_DROSO_GENEORTHO_GENEORTHO.csv'

# Aging Associated
D_Ch_promotes_BioPro = 'Droso_ChemicalEntity_Promotes_BiologicalProcess.csv'
D_Pro_Tiss = 'Droso_Protein_Tissue.csv'
D_Ch_inhibits_BioPro = 'Droso_ChemicalEntity_Inhibits_BiologicalProcess.csv'

D_Gene_promotes_BioPro = 'ALL_Droso_GeneORTHO_Promotes_BiologicalProcess.csv'
D_Gene_BioPro = 'ALL_Droso_GeneORTHO_BiologicalProcess.csv'
D_Gene_inhibits_BioPro = 'ALL_Droso_GeneORTHO_Inhibits_BiologicalProcess.csv'

# D.rerio files

In [15]:
Z_Gene_ph = 'ALL_Zebrafish_GENEORTHO_PHENOTYPE.csv'
Z_Ch_Gene = 'ALL_Zebrafish_CHEMICALENTITY_GENEORTHO.csv'
Z_Gene_Gene = 'ALL_Zebrafish_GENEORTHO_GENEORTHO.csv'

# M.musculus files

In [16]:
M_Gene_ph = 'ALL_Mouse_GENEORTHO_PHENOTYPE.csv'
M_Ch_Gene = 'ALL_MOUSE_CHEMICALENTITY_GENEORTHO.csv'
M_Gene_Gene = 'ALL_MOUSE_GENEORTHO_GENEORTHO.csv'

M_Gene_Noeffect_BioPro = 'Mouse_GeneORTHO_NoEffect_BiologicalProcess.csv'
M_Ch_BioPro = 'Mouse_Chemical_BiologicalProcess.csv'
M_Ch_Ch = 'Mouse_Chemical_Chemical.csv'

M_Gene_promotes_BioPro = 'Mouse_GeneORTHO_Promotes_BiologicalProcess.csv'
M_Gene_BioPro = 'Mouse_GeneORTHO_BiologicalProcess.csv'
M_Gene_inhibits_BioPro = 'Mouse_GeneORTHO_Inhibits_BiologicalProcess.csv'


# Pubmed_id Files

In [17]:
H_pmid_protein = 'PMID_Protein.csv'
H_pmid_cellularcomponent = 'PMID_CellularComp.csv'
H_pmid_chemicalentity = 'PMID_ChemicalEntity.csv'
H_pmid_disease = 'PMID_Disease.csv'
H_pmid_tissue = 'PMID_TISSUE.csv'

# Each species node connecting files

In [18]:
H_species_associatedwith_node = 'Homo_sapiens.csv'

Y_species_associatedwith_node = 'Saccharomyces_cerevisiae.csv'

C_species_associatedwith_node = 'Caenorhabditis_elegans.csv'

D_species_associatedwith_node = 'Drosophila_melanogaster.csv'

Z_species_associatedwith_node = 'Danio_rerio.csv'

M_species_associatedwith_node = 'Mus_musculus.csv'

# All files path list

In [19]:
Allfiles_path_list = [
    H_phenotype_chemicalentity,H_mutation_disease,H_molecularfunction_chemicalentity,H_disease_anatomy,H_chemicalentity_disease,H_disease_disease,
    H_biologicalprocess_gene,H_protein_protein,H_gene_phenotype,H_protein_disease,H_anatomy_gene,H_chemicalentity_biologicalprocess,
    H_disease_gene,H_gene_cellularcomponent,H_chemicalentity_chemicalentity,H_cellularcomponent_gene,H_gene_disease,H_protein_cellularcomponent,
    H_protein_phenotype,H_mutation_protein,H_chemicalentity_gene,H_chemicalentity_tissue,H_chemicalentity_protein,
    H_biologicalprocess_biologicalprocess,
    H_phenotype_phenotype,H_phenotype_gene,H_chemicalentity_inhibits_biologicalprocess,H_gene_inhibits_biologicalprocess,H_protein_biologicalprocess,
    H_gene_promotes_biologicalprocess,
    H_gene_molecularfunction,
    H_gene_pathway,
    H_chemicalentity_pathway,
    H_gene_tissue,
    H_disease_phenotype,
    H_chemicalentity_mutation,
    H_gene_anatomy,
    H_phenotype_disease,
    H_pathway_gene,
    H_disease_chemicalentity,
    H_disease_mutation,
    H_gene_chemicalentity,
    H_protein_pathway,
    H_gene_protein,
    H_gene_noeffect_biologicalprocess,
    H_chemicalentity_promotes_biologicalprocess,
    H_gene_biologicalprocess,
    H_protein_molecularfunction,
    H_mutation_gene,
    H_gene_gene,
    H_molecularfunction_molecularfunction,
    H_gene_mutation,
    H_molecularfunction_biologicalprocess,
    H_protein_tissue,
    H_cellularcomponent_cellularcomponent,
    H_pathway_pathway,
    H_anatomy_anatomy,
    H_biologicalprocess_chemicalentity,
    H_plant_chemicalentity,
    H_plant_disease,

    Y_Gene_ph, Y_Ch_Ch, Y_Ch_Gene, 
    Y_Gene_CellComp, Y_Gene_Gene, 
    Y_Gene_Inhibits_BioPro,
    Y_Gene_Promotes_BioPro, 
    Y_Ch_Inhibits_BioPro,

    C_Gene_ph,C_Ch_Gene,C_Gene_Gene,
    C_Ch_promotes_BioPro,C_Pro_Tiss,
    C_Ch_inhibits_BioPro,
    C_Gene_promotes_BioPro,
    C_Gene_BioPro,
    C_Gene_inhibits_BioPro,

    D_Gene_ph,D_Ch_Gene,D_Gene_Gene,
    D_Ch_promotes_BioPro,D_Pro_Tiss,
    D_Ch_inhibits_BioPro,
    D_Gene_promotes_BioPro,D_Gene_BioPro,
    D_Gene_inhibits_BioPro,

    Z_Gene_ph, Z_Ch_Gene, Z_Gene_Gene,

    M_Gene_ph, M_Ch_Gene, M_Gene_Gene, 
    M_Gene_Noeffect_BioPro, M_Ch_BioPro, 
    M_Ch_Ch, M_Gene_promotes_BioPro,
    M_Gene_BioPro, M_Gene_inhibits_BioPro,

    H_pmid_protein, H_pmid_cellularcomponent, 
    H_pmid_chemicalentity, H_pmid_disease, 
    H_pmid_tissue,

    H_species_associatedwith_node, 
    Y_species_associatedwith_node, 
    C_species_associatedwith_node,               
    D_species_associatedwith_node, 
    Z_species_associatedwith_node, 
    M_species_associatedwith_node,
]

print(len(Allfiles_path_list))

109


# Summary table for all the files

In [24]:
import pandas as pd
import os
from tqdm import tqdm

summary_rows = []
for file_path in tqdm(Allfiles_path_list, desc="Processing files", unit="file"):
    try:
        df = pd.read_csv(file_path, nrows=5)  # ✅ only read first 5 rows
        file = os.path.basename(file_path)

        # Ensure all expected columns exist
        for col in ['relation', 'head_type', 'tail_type', 'head_species', 'tail_species']:
            if col not in df.columns:
                df[col] = 'Unknown'

        # Collect unique sets for each column
        summary_rows.append({
            'filename': file,
            'relation_set': set(df['relation'].dropna().unique()),
            'head_type_set': set(df['head_type'].dropna().unique()),
            'tail_type_set': set(df['tail_type'].dropna().unique()),
            'head_species_set': set(df['head_species'].dropna().unique()),
            'tail_species_set': set(df['tail_species'].dropna().unique())
        })

    except Exception as e:
        print(f"❌ Failed to read {file_path}: {e}")

# Create final DataFrame
summary_df = pd.DataFrame(summary_rows)

# Show result
print("\n✅ Final Summary with Sets:")
summary_df

Processing files: 100%|██████████| 109/109 [00:00<00:00, 172.26file/s]


✅ Final Summary with Sets:


,filename,relation_set,head_type_set,tail_type_set,head_species_set,tail_species_set
0,ALL_PHENOTYPE_CHEMICALENTITY.csv,{Phenotype_ChemicalEntity},{Phenotype},{ChemicalEntity},{Homo sapiens},{Homo sapiens}
1,ALL_MUTATION_DISEASE.csv,{Mutation_Disease},{Mutation},{Disease},{Homo sapiens},{Homo sapiens}
2,ALL_MOLECULARFUNCTION_CHEMICALENTITY.csv,{MolecularFunction_ChemicalEntity},{MolecularFunction},{ChemicalEntity},{Homo sapiens},{Homo sapiens}
3,ALL_DISEASE_ANATOMY.csv,{Disease_Anatomy},{Disease},{Anatomy},{Homo sapiens},{Homo sapiens}
4,ALL_CHEMICALENTITY_DISEASE.csv,{ChemicalEntity_Disease},{ChemicalEntity},{Disease},{Homo sapiens},{Homo sapiens}
...,...,...,...,...,...,...
104,Saccharomyces_cerevisiae.csv,{Species_AssociatedWith},{Species},{CellularComponent},{Unknown},{Unknown}
105,Caenorhabditis_elegans.csv,{Species_AssociatedWith},{Species},{Phenotype},{Unknown},{Unknown}
106,Drosophila_melanogaster.csv,{Species_AssociatedWith},{Species},{Phenotype},{Unknown},{Unknown}
107,Danio_rerio.csv,{Species_AssociatedWith},{Species},{Phenotype},{Unknown},{Unknown}


In [25]:
summary_df.to_csv('All_triple_summary/All_triple_summary.csv',index = None)

# Mapping Function

In [34]:
'''
This function will process each file's head and tail and 
'''

"\nThis function will process each file's head and tail and \n"

In [35]:
# Global mapping to ensure consistency across CSV files
global_mapping = {}

In [36]:
from functools import reduce

def create_mapping_of_nodes_from_pickle(path ,header_list):
    global global_mapping

    if(path.lower().endswith(('.csv'))):
        df = pd.read_csv(path, compression='infer')
    else:
        df = pd.read_pickle(path, compression='infer')

    uniques_per_header = []

    for header in header_list:
        unique_head = df[header].astype(str).unique()
        uniques_per_header.append(unique_head)

    unique_nodes = reduce(np.union1d,uniques_per_header)
    print('Total Unique In This: ',len(unique_nodes))

    for name in unique_nodes:
        if name not in global_mapping:
            global_mapping[name] = len(global_mapping)

    print("Final Mapping Size: ",len(global_mapping))

# Creating mapping file by file

In [37]:
for path in Allfiles_path_list:
    print(path)
    create_mapping_of_nodes_from_pickle(path , ['head','tail'])

/storage/Arushi/070225/070225/Data_to_RelationWise_Triples_Sorting/PHENOTYPE_CHEMICALENTITY/ALL_PHENOTYPE_CHEMICALENTITY.csv
Total Unique In This:  2127
Final Mapping Size:  2127
/storage/Arushi/070225/070225/Data_to_RelationWise_Triples_Sorting/MUTATION_DISEASE/ALL_MUTATION_DISEASE.csv
Total Unique In This:  576
Final Mapping Size:  2703
/storage/Arushi/070225/070225/Data_to_RelationWise_Triples_Sorting/MOLECULARFUNCTION_CHEMICALENTITY/ALL_MOLECULARFUNCTION_CHEMICALENTITY.csv
Total Unique In This:  8288
Final Mapping Size:  10955
/storage/Arushi/070225/070225/Data_to_RelationWise_Triples_Sorting/DISEASE_ANATOMY/ALL_DISEASE_ANATOMY.csv
Total Unique In This:  2107
Final Mapping Size:  13025
/storage/Arushi/070225/070225/Data_to_RelationWise_Triples_Sorting/CHEMICALENTITY_DISEASE/ALL_CHEMICALENTITY_DISEASE.csv


/tmp/ipykernel_2958851/3364301385.py:7: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, compression='infer')


Total Unique In This:  48599
Final Mapping Size:  59296
/storage/Arushi/070225/070225/Data_to_RelationWise_Triples_Sorting/DISEASE_DISEASE/ALL_DISEASE_DISEASE.csv
Total Unique In This:  29732
Final Mapping Size:  81375
/storage/Arushi/070225/070225/Data_to_RelationWise_Triples_Sorting/BIOLOGICALPROCESS_GENE/ALL_BIOLOGIALPROCESS_GENE.csv
Total Unique In This:  30303
Final Mapping Size:  111678
/storage/Arushi/070225/070225/Data_to_RelationWise_Triples_Sorting/PROTEIN_PROTEIN/ALL_PROTEIN_PROTEIN.csv


/tmp/ipykernel_2958851/3364301385.py:7: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, compression='infer')


Total Unique In This:  143399
Final Mapping Size:  255077
/storage/Arushi/070225/070225/Data_to_RelationWise_Triples_Sorting/GENE_PHENOTYPE/ALL_GENE_PHENOTYPE.csv
Total Unique In This:  25932
Final Mapping Size:  266872
/storage/Arushi/070225/070225/Data_to_RelationWise_Triples_Sorting/PROTEIN_DISEASE/ALL_PROTEIN_DISEASE.csv
Total Unique In This:  89821
Final Mapping Size:  274909
/storage/Arushi/070225/070225/Data_to_RelationWise_Triples_Sorting/ANATOMY_GENE/ALL_ANATOMY_GENE.csv
Total Unique In This:  26226
Final Mapping Size:  281994
/storage/Arushi/070225/070225/Data_to_RelationWise_Triples_Sorting/CHEMICALENTITY_BIOLOGICALPROCESS/ALL_CHEMICALENTITY_BIOLOGICALPROCESS.csv
Total Unique In This:  284
Final Mapping Size:  282072
/storage/Arushi/070225/070225/Data_to_RelationWise_Triples_Sorting/DISEASE_GENE/ALL_DISEASE_GENE.csv
Total Unique In This:  38343
Final Mapping Size:  287194
/storage/Arushi/070225/070225/Data_to_RelationWise_Triples_Sorting/GENE_CELLULARCOMPONENT/ALL_GENE_CELLU

/tmp/ipykernel_2958851/3364301385.py:7: DtypeWarning: Columns (0,11) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, compression='infer')


Total Unique In This:  53784
Final Mapping Size:  330301
/storage/Arushi/070225/070225/Data_to_RelationWise_Triples_Sorting/CELLULARCOMPONENT_GENE/ALL_CELLCOMPONENT_GENE.csv
Total Unique In This:  20327
Final Mapping Size:  330383
/storage/Arushi/070225/070225/Data_to_RelationWise_Triples_Sorting/GENE_DISEASE/ALL_GENE_DISEASE.csv
Total Unique In This:  52182
Final Mapping Size:  346154
/storage/Arushi/070225/070225/Data_to_RelationWise_Triples_Sorting/PROTEIN_CELLULARCOMPONENT/ALL_PROTEIN_CELLULARCOMPONENT.csv


/tmp/ipykernel_2958851/3364301385.py:7: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, compression='infer')


Total Unique In This:  318007
Final Mapping Size:  528456
/storage/Arushi/070225/070225/Data_to_RelationWise_Triples_Sorting/PROTEIN_PHENOTYPE/ALL_PROTEIN_PHENOTYPE.csv
Total Unique In This:  352
Final Mapping Size:  528477
/storage/Arushi/070225/070225/Data_to_RelationWise_Triples_Sorting/MUTATION_PROTEIN/ALL_MUTATION_PROTEIN.csv
Total Unique In This:  1545215
Final Mapping Size:  2062237
/storage/Arushi/070225/070225/Data_to_RelationWise_Triples_Sorting/CHEMICALENTITY_GENE/ALL_CHEMICALENTITY_GENE2.csv


/tmp/ipykernel_2958851/3364301385.py:7: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, compression='infer')


Total Unique In This:  551378
Final Mapping Size:  2573930
/storage/Arushi/070225/070225/Data_to_RelationWise_Triples_Sorting/CHEMICALENTITY_TISSUE/ALL_CHEMICALENTITY_TISSUE.csv
Total Unique In This:  231
Final Mapping Size:  2573942
/storage/Arushi/070225/070225/Data_to_RelationWise_Triples_Sorting/CHEMICALENTITY_PROTEIN/ALL_CHEMICALENTITY_PROTEIN2.csv


/tmp/ipykernel_2958851/3364301385.py:7: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, compression='infer')


Total Unique In This:  378295
Final Mapping Size:  2721423
/storage/Arushi/070225/070225/Data_to_RelationWise_Triples_Sorting/BIOLOGICALPROCESS_BIOLOGICALPROCESS/ALL_BIOLOGICALPROCESS_BIOLOGICALPROCESS.csv
Total Unique In This:  29056
Final Mapping Size:  2738019
/storage/Arushi/070225/070225/Data_to_RelationWise_Triples_Sorting/PHENOTYPE_PHENOTYPE/All_PHENOTYPE_PHENOTYPE.csv
Total Unique In This:  16016
Final Mapping Size:  2743956
/storage/Arushi/070225/070225/Data_to_RelationWise_Triples_Sorting/PHENOTYPE_GENE/ALL_PHENOTYPE_GENE.csv
Total Unique In This:  1962
Final Mapping Size:  2743956
/storage/Arushi/070225/070225/Data_to_RelationWise_Triples_Sorting/CHEMICALENTITY_INHIBITS_BIOLOGICALPROCESS/ALL_CHEMICALENTITY_INHIBITS_BIOLOGICALPROCESS.csv
Total Unique In This:  6693
Final Mapping Size:  2746846
/storage/Arushi/070225/070225/Data_to_RelationWise_Triples_Sorting/GENE_INHIBITS_BIOLOGICALPROCESS/ALL_GENE_INHIBITS_BIOLOGICALPROCESS.csv
Total Unique In This:  924
Final Mapping Size:

/tmp/ipykernel_2958851/3364301385.py:7: DtypeWarning: Columns (2,10) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, compression='infer')


Total Unique In This:  10570204
Final Mapping Size:  18939011
/storage/Arushi/CKG_PMID_processed/PMID_Disease.csv
Total Unique In This:  14873524
Final Mapping Size:  25909268
/storage/Arushi/CKG_PMID_processed/PMID_TISSUE.csv
Total Unique In This:  18918203
Final Mapping Size:  30159063
/storage/Arushi/070225/170525_sakshi/Giving_each_file_Species_name_and_Species_Nodes/Homo_sapiens.csv
Total Unique In This:  2589074
Final Mapping Size:  30159165
/storage/Arushi/070225/170525_sakshi/Giving_each_file_Species_name_and_Species_Nodes/Saccharomyces_cerevisiae.csv


/tmp/ipykernel_2958851/3364301385.py:7: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, compression='infer')


Total Unique In This:  327768
Final Mapping Size:  30159166
/storage/Arushi/070225/170525_sakshi/Giving_each_file_Species_name_and_Species_Nodes/Caenorhabditis_elegans.csv


/tmp/ipykernel_2958851/3364301385.py:7: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, compression='infer')


Total Unique In This:  323572
Final Mapping Size:  30159167
/storage/Arushi/070225/170525_sakshi/Giving_each_file_Species_name_and_Species_Nodes/Drosophila_melanogaster.csv


/tmp/ipykernel_2958851/3364301385.py:7: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, compression='infer')


Total Unique In This:  348182
Final Mapping Size:  30159168
/storage/Arushi/070225/170525_sakshi/Giving_each_file_Species_name_and_Species_Nodes/Danio_rerio.csv


/tmp/ipykernel_2958851/3364301385.py:7: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, compression='infer')


Total Unique In This:  441187
Final Mapping Size:  30159169
/storage/Arushi/070225/170525_sakshi/Giving_each_file_Species_name_and_Species_Nodes/Mus_musculus.csv


/tmp/ipykernel_2958851/3364301385.py:7: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, compression='infer')


Total Unique In This:  440930
Final Mapping Size:  30159170


# Final Mappings

In [38]:
unique_node_id = pd.DataFrame(data={
    'Node': global_mapping.keys(),
    'MappedID': global_mapping.values(),
})

unique_node_id

,Node,MappedID
0,10100,0
1,101033550,1
2,10113978,2
3,10133,3
4,10297,4
...,...,...
30159165,Saccharomyces cerevisiae,30159165
30159166,Caenorhabditis elegans,30159166
30159167,Drosophila melanogaster,30159167
30159168,Danio rerio,30159168


In [40]:
unique_node_id.to_pickle('Store_House/node_id_Mapping_Evo_KG.pkl')

In [41]:
df = pd.read_pickle('Store_House/node_id_Mapping_Evo_KG.pkl')

if (df['MappedID'] >= 0).all():
    print(f"All elements in column '{'MappedID'}' are positive.")
else:
    print(f"Not all elements in column '{'MappedID'}' are positive.")
df

All elements in column 'MappedID' are positive.


,Node,MappedID
0,10100,0
1,101033550,1
2,10113978,2
3,10133,3
4,10297,4
...,...,...
30159165,Saccharomyces cerevisiae,30159165
30159166,Caenorhabditis elegans,30159166
30159167,Drosophila melanogaster,30159167
30159168,Danio rerio,30159168


# Edges in COO format

In [42]:
# from pykeen.triples import TriplesFactory , CoreTriplesFactory

In [43]:
edge_mapping =relation_to_id = {
    "Phenotype_ChemicalEntity": 0,
    "Mutation_Disease": 1,
    "MolecularFunction_ChemicalEntity": 2,
    "Disease_Anatomy": 3,
    "ChemicalEntity_Disease": 4,
    "Disease_Disease": 5,
    "BiologicalProcess_Gene": 6,
    "Protein_Protein": 7,
    "Gene_Phenotype": 8,
    "Protein_Disease": 9,
    "Anatomy_Gene": 10,
    "ChemicalEntity_BiologicalProcess": 11,
    "Disease_Gene": 12,
    "Gene_CellularComponent": 13,
    "ChemicalEntity_ChemicalEntity": 14,
    "CellularComponent_Gene": 15,
    "Gene_Disease": 16,
    "Protein_CellularComponent": 17,
    "Protein_Phenotype": 18,
    "Mutation_Protein": 19,
    "ChemicalEntity_Gene": 20,
    "ChemicalEntity_Tissue": 21,
    "ChemicalEntity_Protein": 22,
    "BiologicalProcess_BiologicalProcess": 23,
    "Phenotype_Phenotype": 24,
    "Phenotype_Gene": 25,
    "ChemicalEntity_Inhibits_BiologicalProcess": 26,
    "Gene_Inhibits_BiologicalProcess": 27,
    "Protein_BiologicalProcess": 28,
    "Gene_Promotes_BiologicalProcess": 29,
    "Gene_MolecularFunction": 30,
    "Gene_Pathway": 31,
    "ChemicalEntity_Pathway": 32,
    "Gene_Tissue": 33,
    "Disease_Phenotype": 34,
    "ChemicalEntity_Mutation": 35,
    "Gene_Anatomy": 36,
    "Phenotype_Disease": 37,
    "Pathway_Gene": 38,
    "Disease_ChemicalEntity": 39,
    "Disease_Mutation": 40,
    "Gene_ChemicalEntity": 41,
    "Protein_Pathway": 42,
    "Gene_Protein": 43,
    "Gene_Noeffect_BiologicalProcess": 44,
    "ChemicalEntity_Promotes_BiologicalProcess": 45,
    "Gene_BiologicalProcess": 46,
    "Protein_MolecularFunction": 47,
    "Mutation_Gene": 48,
    "Gene_Gene": 49,
    "MolecularFunction_MolecularFunction": 50,
    "Gene_Mutation": 51,
    "MolecularFunction_BiologicalProcess": 52,
    "Protein_Tissue": 53,
    "CellularComponent_CellularComponent": 54,
    "Pathway_Pathway": 55,
    "Anatomy_Anatomy": 56,
    "BiologicalProcess_ChemicalEntity": 57,
    "PlantExtract_ChemicalEntity": 58,
    "PlantExtract_Disease": 59,
    "Pmid_CellularComponent": 60,
    "Pmid_ChemicalEntity": 61,
    "Pmid_Disease": 62,
    "Pmid_Protein": 63,
    "Pmid_Tissue": 64,
    "Species_associatedwith_nodes": 65
}

In [44]:
head_index_list = []
tail_index_list = []
edge_type_list = []

# Function to convert triples in MappedID format

In [45]:

def triples_as_mappedID(path, head_type, tail_type):
    if path.lower().endswith('.csv'):
        df = pd.read_csv(path, compression='infer')
    else:
        df = pd.read_pickle(path, compression='infer')

    head_map_path = f'Store_House/{head_type}_id_H_KG.pkl'
    tail_map_path = f'Store_House/{tail_type}_id_H_KG.pkl'

    head_df = pd.read_pickle(head_map_path, compression='infer')
    tail_df = pd.read_pickle(tail_map_path, compression='infer')

    head_type_cap = head_type.capitalize()
    tail_type_cap = tail_type.capitalize()

    # Ensure consistent dtype (string) for merge columns
    df['head'] = df['head'].astype(str)
    df['tail'] = df['tail'].astype(str)
    head_df[head_type_cap] = head_df[head_type_cap].astype(str)
    tail_df[tail_type_cap] = tail_df[tail_type_cap].astype(str)

    # Merge and map head IDs
    head_id = pd.merge(df[['head']], head_df,
                       left_on='head', right_on=head_type_cap, how='left')
    head_id_tensor = torch.from_numpy(head_id['MappedID'].values).to(dtype=torch.int64)
    print('Head Tensor:', head_id_tensor)

    # Merge and map tail IDs
    tail_id = pd.merge(df[['tail']], tail_df,
                       left_on='tail', right_on=tail_type_cap, how='left')
    tail_id_tensor = torch.from_numpy(tail_id['MappedID'].values).to(dtype=torch.int64)
    print('Tail Tensor:', tail_id_tensor)

    # Build COO edge index
    edge_index = torch.stack([head_id_tensor, tail_id_tensor], dim=0)
    print('\nEdges in COO format:')
    print(edge_index)

    return edge_index

# Converting the triples

In [48]:
head_index_list = []
tail_index_list = []
edge_type_list = []

triples_to_process = [
    (H_phenotype_chemicalentity, "Phenotype_ChemicalEntity"),
    (H_mutation_disease, "Mutation_Disease"),
    (H_molecularfunction_chemicalentity, "MolecularFunction_ChemicalEntity"),
    (H_disease_anatomy, "Disease_Anatomy"),
    (H_chemicalentity_disease, "ChemicalEntity_Disease"),
    (H_disease_disease, "Disease_Disease"),
    (H_biologicalprocess_gene, "BiologicalProcess_Gene"),
    (H_protein_protein, "Protein_Protein"),
    (H_gene_phenotype, "Gene_Phenotype"),
    (H_protein_disease, "Protein_Disease"),
    (H_anatomy_gene, "Anatomy_Gene"),
    (H_chemicalentity_biologicalprocess, "ChemicalEntity_BiologicalProcess"),
    (H_disease_gene, "Disease_Gene"),
    (H_gene_cellularcomponent, "Gene_CellularComponent"),
    (H_chemicalentity_chemicalentity, "ChemicalEntity_ChemicalEntity"),
    (H_cellularcomponent_gene, "CellularComponent_Gene"),
    (H_gene_disease, "Gene_Disease"),
    (H_protein_cellularcomponent, "Protein_CellularComponent"),
    (H_protein_phenotype, "Protein_Phenotype"),
    (H_mutation_protein, "Mutation_Protein"),
    (H_chemicalentity_gene, "ChemicalEntity_Gene"),
    (H_chemicalentity_tissue, "ChemicalEntity_Tissue"),
    (H_chemicalentity_protein, "ChemicalEntity_Protein"),
    (H_biologicalprocess_biologicalprocess, "BiologicalProcess_BiologicalProcess"),
    (H_phenotype_phenotype, "Phenotype_Phenotype"),
    (H_phenotype_gene, "Phenotype_Gene"),
    (H_chemicalentity_inhibits_biologicalprocess, "ChemicalEntity_Inhibits_BiologicalProcess"),
    (H_gene_inhibits_biologicalprocess, "Gene_Inhibits_BiologicalProcess"),
    (H_protein_biologicalprocess, "Protein_BiologicalProcess"),
    (H_gene_promotes_biologicalprocess, "Gene_Promotes_BiologicalProcess"),
    (H_gene_molecularfunction, "Gene_MolecularFunction"),
    (H_gene_pathway, "Gene_Pathway"),
    (H_chemicalentity_pathway, "ChemicalEntity_Pathway"),
    (H_gene_tissue, "Gene_Tissue"),
    (H_disease_phenotype, "Disease_Phenotype"),
    (H_chemicalentity_mutation, "ChemicalEntity_Mutation"),
    (H_gene_anatomy, "Gene_Anatomy"),
    (H_phenotype_disease, "Phenotype_Disease"),
    (H_pathway_gene, "Pathway_Gene"),
    (H_disease_chemicalentity, "Disease_ChemicalEntity"),
    (H_disease_mutation, "Disease_Mutation"),
    (H_gene_chemicalentity, "Gene_ChemicalEntity"),
    (H_protein_pathway, "Protein_Pathway"),
    (H_gene_protein, "Gene_Protein"),
    (H_gene_noeffect_biologicalprocess, "Gene_Noeffect_BiologicalProcess"),
    (H_chemicalentity_promotes_biologicalprocess, "ChemicalEntity_Promotes_BiologicalProcess"),
    (H_gene_biologicalprocess, "Gene_BiologicalProcess"),
    (H_protein_molecularfunction, "Protein_MolecularFunction"),
    (H_mutation_gene, "Mutation_Gene"),
    (H_gene_gene, "Gene_Gene"),
    (H_molecularfunction_molecularfunction, "MolecularFunction_MolecularFunction"),
    (H_gene_mutation, "Gene_Mutation"),
    (H_molecularfunction_biologicalprocess, "MolecularFunction_BiologicalProcess"),
    (H_protein_tissue, "Protein_Tissue"),
    (H_cellularcomponent_cellularcomponent, "CellularComponent_CellularComponent"),
    (H_pathway_pathway, "Pathway_Pathway"),
    (H_anatomy_anatomy, "Anatomy_Anatomy"),
    (H_biologicalprocess_chemicalentity, "BiologicalProcess_ChemicalEntity"),
    (H_plant_chemicalentity, "PlantExtract_ChemicalEntity"),
    (H_plant_disease, "PlantExtract_Disease"),

    (Y_Gene_ph, "Gene_Phenotype"),
    (Y_Ch_Inhibits_BioPro, "ChemicalEntity_Inhibits_BiologicalProcess"),
    (Y_Gene_CellComp, "Gene_CellularComponent"),
    (Y_Ch_Ch, "ChemicalEntity_ChemicalEntity"),
    (Y_Ch_Gene, "ChemicalEntity_Gene"),
    (Y_Gene_Inhibits_BioPro, "Gene_Inhibits_BiologicalProcess"),
    (Y_Gene_Promotes_BioPro , "Gene_Promotes_BiologicalProcess"),
    (Y_Gene_Gene, "Gene_Gene"),

    (C_Gene_ph, "Gene_Phenotype"),
    (C_Ch_Gene, "ChemicalEntity_Gene"),
    (C_Gene_Gene, "Gene_Gene"),
    (C_Ch_promotes_BioPro, "ChemicalEntity_Promotes_BiologicalProcess"),
    (C_Pro_Tiss, "Protein_Tissue"),
    (C_Ch_inhibits_BioPro, "ChemicalEntity_Inhibits_BiologicalProcess"),
    (C_Gene_promotes_BioPro , "Gene_Promotes_BiologicalProcess"),
    (C_Gene_BioPro, "Gene_BiologicalProcess"),
    (C_Gene_inhibits_BioPro, "Gene_Inhibits_BiologicalProcess"),

    (D_Gene_ph, "Gene_Phenotype"),
    (D_Ch_Gene, "ChemicalEntity_Gene"),
    (D_Gene_Gene, "Gene_Gene"),
    (D_Ch_promotes_BioPro, "ChemicalEntity_Promotes_BiologicalProcess"),
    (D_Pro_Tiss, "Protein_Tissue"),
    (D_Ch_inhibits_BioPro, "ChemicalEntity_Inhibits_BiologicalProcess"),
    (D_Gene_promotes_BioPro , "Gene_Promotes_BiologicalProcess"),
    (D_Gene_BioPro, "Gene_BiologicalProcess"),
    (D_Gene_inhibits_BioPro, "Gene_Inhibits_BiologicalProcess"),

    (Z_Gene_ph, "Gene_Phenotype"),
    (Z_Ch_Gene, "ChemicalEntity_Gene"),
    (Z_Gene_Gene, "Gene_Gene"),   

    (M_Gene_ph, "Gene_Phenotype"),
    (M_Ch_Gene, "ChemicalEntity_Gene"),
    (M_Gene_Gene, "Gene_Gene"),
    (M_Gene_Noeffect_BioPro, "Gene_Noeffect_BiologicalProcess"),
    (M_Ch_BioPro, "ChemicalEntity_BiologicalProcess"),
    (M_Ch_Ch, "ChemicalEntity_ChemicalEntity"),
    (M_Gene_promotes_BioPro , "Gene_Promotes_BiologicalProcess"),
    (M_Gene_BioPro, "Gene_BiologicalProcess"),
    (M_Gene_inhibits_BioPro, "Gene_Inhibits_BiologicalProcess"),

    (H_pmid_cellularcomponent, "Pmid_CellularComponent"),
    (H_pmid_chemicalentity, "Pmid_ChemicalEntity"),
    (H_pmid_disease, "Pmid_Disease"),
    (H_pmid_protein, "Pmid_Protein"),
    (H_pmid_tissue, "Pmid_Tissue"),
    (H_species_associatedwith_node, "Species_associatedwith_nodes"),
    (Y_species_associatedwith_node, "Species_associatedwith_nodes"),
    (C_species_associatedwith_node, "Species_associatedwith_nodes"),
    (D_species_associatedwith_node, "Species_associatedwith_nodes"),
    (Z_species_associatedwith_node, "Species_associatedwith_nodes"),
    (M_species_associatedwith_node, "Species_associatedwith_nodes")
    
]

In [49]:
# Loop through each triple
for path, relation_name in triples_to_process:
    print(f"\nProcessing: {relation_name}")
    
    edge_index = triples_as_mappedID(path, 'node', 'node')
    
    # Sanity check
    if edge_index.size(0) != 2:
        print("Invalid COO shape!")
        continue

    head_ids = edge_index[0]
    tail_ids = edge_index[1]
    num_edges = len(head_ids)
    edge_type = torch.full((num_edges,), edge_mapping[relation_name], dtype=torch.int64)

    print('Edge Type:')
    print(edge_type)

    head_index_list.append(head_ids)
    tail_index_list.append(tail_ids)
    edge_type_list.append(edge_type)

    if torch.all(head_ids >= 0) and torch.all(tail_ids >= 0):
        print("All Good")
    else:
        print("Invalid indices detected.")



Processing: Phenotype_ChemicalEntity
Head Tensor: tensor([1451, 1658, 1228,  ..., 1378, 1308, 1570])
Tail Tensor: tensor([  18,   18,   18,  ..., 1085, 1085, 1085])

Edges in COO format:
tensor([[1451, 1658, 1228,  ..., 1378, 1308, 1570],
        [  18,   18,   18,  ..., 1085, 1085, 1085]])
Edge Type:
tensor([0, 0, 0,  ..., 0, 0, 0])
All Good

Processing: Mutation_Disease
Head Tensor: tensor([2305, 2306, 2307, 2308, 2309, 2310, 2311, 2312, 2313, 2314, 2315, 2316,
        2317, 2318, 2319, 2320, 2320, 2320, 2320, 2320, 2320, 2321, 2322, 2322,
        2323, 2324, 2325, 2326, 2326, 2326, 2327, 2327, 2327, 2328, 2329, 2329,
        2329, 2330, 2331, 2331, 2331, 2332, 2333, 2333, 2334, 2335, 2336, 2337,
        2338, 2339, 2339, 2340, 2341, 2342, 2343, 2344, 2345, 2346, 2346, 2346,
        2346, 2347, 2347, 2348, 2349, 2350, 2351, 2352, 2353, 2354, 2355, 2356,
        2357, 2358, 2358, 2359, 2360, 2360, 2360, 2360, 2361, 2361, 2361, 2362,
        2362, 2363, 2364, 2365, 2366, 2366, 2367, 2

/tmp/ipykernel_2958851/1798996901.py:3: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, compression='infer')


Head Tensor: tensor([40467, 40467, 40467,  ..., 54949, 54950, 54951])
Tail Tensor: tensor([11637,  2257, 56012,  ..., 51524, 51280, 54107])

Edges in COO format:
tensor([[40467, 40467, 40467,  ..., 54949, 54950, 54951],
        [11637,  2257, 56012,  ..., 51524, 51280, 54107]])
Edge Type:
tensor([4, 4, 4,  ..., 4, 4, 4])
All Good

Processing: Disease_Disease
Head Tensor: tensor([59296, 51032, 51033,  ..., 81374, 81374, 81374])
Tail Tensor: tensor([11171, 59392, 59449,  ..., 11137, 71535, 11779])

Edges in COO format:
tensor([[59296, 51032, 51033,  ..., 81374, 81374, 81374],
        [11171, 59392, 59449,  ..., 11137, 71535, 11779]])
Edge Type:
tensor([5, 5, 5,  ..., 5, 5, 5])
All Good

Processing: BiologicalProcess_Gene
Head Tensor: tensor([86637, 86637, 86637,  ..., 99094, 99095, 99095])
Tail Tensor: tensor([ 81868, 101375, 101829,  ...,  81920,  81462,  81540])

Edges in COO format:
tensor([[ 86637,  86637,  86637,  ...,  99094,  99095,  99095],
        [ 81868, 101375, 101829,  ..., 

/tmp/ipykernel_2958851/1798996901.py:3: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, compression='infer')


Head Tensor: tensor([111679, 111679, 111679,  ..., 255076, 255076, 255076])
Tail Tensor: tensor([115385, 116520, 118194,  ..., 252837, 253682, 253842])

Edges in COO format:
tensor([[111679, 111679, 111679,  ..., 255076, 255076, 255076],
        [115385, 116520, 118194,  ..., 252837, 253682, 253842]])
Edge Type:
tensor([7, 7, 7,  ..., 7, 7, 7])
All Good

Processing: Gene_Phenotype
Head Tensor: tensor([ 81375,  81375,  81376,  ..., 111677, 111677, 111677])
Tail Tensor: tensor([  1500, 264934, 256012,  ..., 256930, 258362,   1650])

Edges in COO format:
tensor([[ 81375,  81375,  81376,  ..., 111677, 111677, 111677],
        [  1500, 264934, 256012,  ..., 256930, 258362,   1650]])
Edge Type:
tensor([8, 8, 8,  ..., 8, 8, 8])
All Good

Processing: Protein_Disease
Head Tensor: tensor([111679, 111679, 111679,  ..., 274908, 274908, 274908])
Tail Tensor: tensor([54952, 54954, 74823,  ..., 59209, 59260, 81365])

Edges in COO format:
tensor([[111679, 111679, 111679,  ..., 274908, 274908, 274908],

/tmp/ipykernel_2958851/1798996901.py:3: DtypeWarning: Columns (0,11) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, compression='infer')


Head Tensor: tensor([289784, 289784, 289784,  ..., 330300, 330300, 330300])
Tail Tensor: tensor([290865,   2750,  13655,  ...,  43718,  47358,  50601])

Edges in COO format:
tensor([[289784, 289784, 289784,  ..., 330300, 330300, 330300],
        [290865,   2750,  13655,  ...,  43718,  47358,  50601]])
Edge Type:
tensor([14, 14, 14,  ..., 14, 14, 14])
All Good

Processing: CellularComponent_Gene
Head Tensor: tensor([287270, 287270, 287270,  ..., 289389, 289389, 289390])
Tail Tensor: tensor([ 85486,  85487,  85488,  ..., 104942, 109174,  85461])

Edges in COO format:
tensor([[287270, 287270, 287270,  ..., 289389, 289389, 289390],
        [ 85486,  85487,  85488,  ..., 104942, 109174,  85461]])
Edge Type:
tensor([15, 15, 15,  ..., 15, 15, 15])
All Good

Processing: Gene_Disease
Head Tensor: tensor([330383,  81375,  81375,  ..., 111677, 111677, 111677])
Tail Tensor: tensor([ 57488, 330470, 330517,  ...,  58499,  58886,   2304])

Edges in COO format:
tensor([[330383,  81375,  81375,  ..., 1

/tmp/ipykernel_2958851/1798996901.py:3: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, compression='infer')


Head Tensor: tensor([346154, 346155, 346155,  ..., 274908, 274908, 274908])
Tail Tensor: tensor([287502, 287413, 395197,  ..., 289251, 289301, 289346])

Edges in COO format:
tensor([[346154, 346155, 346155,  ..., 274908, 274908, 274908],
        [287502, 287413, 395197,  ..., 289251, 289301, 289346]])
Edge Type:
tensor([17, 17, 17,  ..., 17, 17, 17])
All Good

Processing: Protein_Phenotype
Head Tensor: tensor([112323, 112323, 112323, 112323, 112323, 112323, 112323, 112323, 112323,
        112323, 112779, 112779, 112779, 112779, 112779, 112779, 112779, 112779,
        112779, 112779, 112779, 112878, 112878, 112878, 112878, 112990, 112990,
        112990, 112990, 112990, 112990, 112990, 112990, 112990, 112990, 112990,
        112990, 112990, 112990, 112990, 112990, 112990, 112990, 112990, 112990,
        113171, 113171, 113171, 113171, 113171, 113171, 113706, 113706, 113706,
        113706, 113706, 113706, 113706, 113706, 113706, 113706, 113718, 113718,
        113718, 113718, 113718, 11

/tmp/ipykernel_2958851/1798996901.py:3: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, compression='infer')


Head Tensor: tensor([ 289784,  289784,   40467,  ..., 2573894, 2573895, 2573896])
Tail Tensor: tensor([255180, 266089,  83429,  ..., 100310,  82970,  86386])

Edges in COO format:
tensor([[ 289784,  289784,   40467,  ..., 2573894, 2573895, 2573896],
        [ 255180,  266089,   83429,  ...,  100310,   82970,   86386]])
Edge Type:
tensor([20, 20, 20,  ..., 20, 20, 20])
All Good

Processing: ChemicalEntity_Tissue
Head Tensor: tensor([ 47913,  15519,  35797,  36478,   3363,   3380,   4093,   4098,   4117,
          4117,    334,   4647,  42761,  42848,  45747,  45747,  45747,  45747,
          5337,   5337,  47376,  47383,  48752,   1022,   1022,  48848,  48848,
        282060,  49455,  49455,  49455,   6078,   1047,  50073,  51007,   2728,
         14057,   2807,  14305,   2824,   2824,   2825,  15246,  15630,  37646,
        282024,  38606,  38606,    239,  41413,  41413,  42826,  45357,    863,
         45682,  45682,    865,   5339,  45824,  45824,  45835,    879,    879,
         458

/tmp/ipykernel_2958851/1798996901.py:3: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, compression='infer')


Head Tensor: tensor([2573942, 2573942, 2573942,  ..., 2720254, 2720254, 2720254])
Tail Tensor: tensor([145292, 163455, 172359,  ..., 248754, 249317, 249356])

Edges in COO format:
tensor([[2573942, 2573942, 2573942,  ..., 2720254, 2720254, 2720254],
        [ 145292,  163455,  172359,  ...,  248754,  249317,  249356]])
Edge Type:
tensor([22, 22, 22,  ..., 22, 22, 22])
All Good

Processing: BiologicalProcess_BiologicalProcess
Head Tensor: tensor([2721423, 2721423,   86637,  ..., 2738018, 2738018, 2738018])
Tail Tensor: tensor([2728673,   93254,   88234,  ..., 2732917, 2734578, 2738017])

Edges in COO format:
tensor([[2721423, 2721423,   86637,  ..., 2738018, 2738018, 2738018],
        [2728673,   93254,   88234,  ..., 2732917, 2734578, 2738017]])
Edge Type:
tensor([23, 23, 23,  ..., 23, 23, 23])
All Good

Processing: Phenotype_Phenotype
Head Tensor: tensor([ 256013,  256013,  256013,  ..., 2743955, 2743955,  265286])
Tail Tensor: tensor([ 256084,  256929,  258361,  ...,    1327, 2741353

/tmp/ipykernel_2958851/1798996901.py:3: DtypeWarning: Columns (2,10) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, compression='infer')


Head Tensor: tensor([ 5059982,  4855561,  4941704,  ..., 15762308, 15130390, 15706852])
Tail Tensor: tensor([47996, 47996, 47996,  ..., 38210, 38210, 38210])

Edges in COO format:
tensor([[ 5059982,  4855561,  4941704,  ..., 15762308, 15130390, 15706852],
        [   47996,    47996,    47996,  ...,    38210,    38210,    38210]])
Edge Type:
tensor([61, 61, 61,  ..., 61, 61, 61])
All Good

Processing: Pmid_Disease
Head Tensor: tensor([ 5043277, 15592843, 11831120,  ..., 25354092, 24792326, 19730299])
Tail Tensor: tensor([54952, 54952, 54952,  ..., 81374, 81374, 81374])

Edges in COO format:
tensor([[ 5043277, 15592843, 11831120,  ..., 25354092, 24792326, 19730299],
        [   54952,    54952,    54952,  ...,    81374,    81374,    81374]])
Edge Type:
tensor([62, 62, 62,  ..., 62, 62, 62])
All Good

Processing: Pmid_Protein
Head Tensor: tensor([ 5075498,  4515401,  4132325,  ...,  8061773, 10405068, 10110772])
Tail Tensor: tensor([165212, 165212, 165212,  ..., 111830, 111830, 111830])


/tmp/ipykernel_2958851/1798996901.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, compression='infer')


Head Tensor: tensor([30159165, 30159165, 30159165,  ..., 30159165, 30159165, 30159165])
Tail Tensor: tensor([ 287502, 3257981,  287447,  ..., 3258071, 3258072, 3258073])

Edges in COO format:
tensor([[30159165, 30159165, 30159165,  ..., 30159165, 30159165, 30159165],
        [  287502,  3257981,   287447,  ...,  3258071,  3258072,  3258073]])
Edge Type:
tensor([65, 65, 65,  ..., 65, 65, 65])
All Good

Processing: Species_associatedwith_nodes


/tmp/ipykernel_2958851/1798996901.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, compression='infer')


Head Tensor: tensor([30159166, 30159166, 30159166,  ..., 30159166, 30159166, 30159166])
Tail Tensor: tensor([3273417, 3273825, 3273832,  ..., 3272780, 3272781, 3292609])

Edges in COO format:
tensor([[30159166, 30159166, 30159166,  ..., 30159166, 30159166, 30159166],
        [ 3273417,  3273825,  3273832,  ...,  3272780,  3272781,  3292609]])
Edge Type:
tensor([65, 65, 65,  ..., 65, 65, 65])
All Good

Processing: Species_associatedwith_nodes


/tmp/ipykernel_2958851/1798996901.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, compression='infer')


Head Tensor: tensor([30159167, 30159167, 30159167,  ..., 30159167, 30159167, 30159167])
Tail Tensor: tensor([3296316, 3295463, 3295471,  ..., 3310448, 3310565, 2798130])

Edges in COO format:
tensor([[30159167, 30159167, 30159167,  ..., 30159167, 30159167, 30159167],
        [ 3296316,  3295463,  3295471,  ...,  3310448,  3310565,  2798130]])
Edge Type:
tensor([65, 65, 65,  ..., 65, 65, 65])
All Good

Processing: Species_associatedwith_nodes


/tmp/ipykernel_2958851/1798996901.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, compression='infer')


Head Tensor: tensor([30159168, 30159168, 30159168,  ..., 30159168, 30159168, 30159168])
Tail Tensor: tensor([3313140, 3316834, 3321633,  ..., 3360869, 3360870, 3360887])

Edges in COO format:
tensor([[30159168, 30159168, 30159168,  ..., 30159168, 30159168, 30159168],
        [ 3313140,  3316834,  3321633,  ...,  3360869,  3360870,  3360887]])
Edge Type:
tensor([65, 65, 65,  ..., 65, 65, 65])
All Good

Processing: Species_associatedwith_nodes


/tmp/ipykernel_2958851/1798996901.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, compression='infer')


Head Tensor: tensor([30159169, 30159169, 30159169,  ..., 30159169, 30159169, 30159169])
Tail Tensor: tensor([3390446, 3390463, 3379094,  ..., 3384371, 3388564, 3390089])

Edges in COO format:
tensor([[30159169, 30159169, 30159169,  ..., 30159169, 30159169, 30159169],
        [ 3390446,  3390463,  3379094,  ...,  3384371,  3388564,  3390089]])
Edge Type:
tensor([65, 65, 65,  ..., 65, 65, 65])
All Good


In [50]:
final_head_index = torch.cat(head_index_list , dim = 0)
#final_head_index = torch.tensor([item for tensor in head_index_list for item in tensor] , dtype= torch.int64)
final_tail_index = torch.cat(tail_index_list , dim = 0)
final_edge_type = torch.cat(edge_type_list , dim = 0)

print(final_head_index)
print(final_tail_index)
print(final_edge_type)

final_edge_index = torch.stack([final_head_index,final_tail_index] , dim = 0)

if torch.all(final_head_index >= 0):
    print('All Good')
else:
    print("Invalid indices detected.")

tensor([    1451,     1658,     1228,  ..., 30159169, 30159169, 30159169])
tensor([     18,      18,      18,  ..., 3384371, 3388564, 3390089])
tensor([ 0,  0,  0,  ..., 65, 65, 65])
All Good


In [51]:
if torch.all(final_tail_index >= 0):
    print('All |Good')
else:
    print("Invalid indices detected.")

All |Good


In [52]:
torch.save(final_edge_index ,'Store_House/EvoAge_edge_index_1.pt')
torch.save(final_edge_type ,'Store_House/EvpAge_edge_type_1.pt')

In [53]:
edge_index = torch.load('Store_House/EvoAge_edge_index_1.pt')
edge_type = torch.load('Store_House/EvpAge_edge_type_1.pt')

if torch.all(edge_index >= 0):
    print('All Good')
else:
    print("Invalid indices detected.")

n = len(edge_type)

mapped_triples = torch.stack((edge_index[0], edge_type, edge_index[1]), dim=1)

print(mapped_triples)

All Good
tensor([[    1451,        0,       18],
        [    1658,        0,       18],
        [    1228,        0,       18],
        ...,
        [30159169,       65,  3384371],
        [30159169,       65,  3388564],
        [30159169,       65,  3390089]])


In [54]:
mapped_triples[:, [0, 2]].min().item()+1

1

In [55]:
mapped_triples[:, [0, 2]].max().item()+1

30159170

In [56]:
mapped_triples.shape

torch.Size([1049367477, 3])

In [57]:
torch.save(mapped_triples, 'EvoAge_KG.pt')